# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ianma/Documents/Simula/LAB7/LAB7.cache/wt [current_project]
set_property parent.project_path C:/Users/ianma/Documents/Simula/LAB7/LAB7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/ianma/Documents/Simula/LAB7/LAB7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/ianma/Documents/Simula/LAB7/LAB7.srcs/sources_1/new/Divisor_de_F.vhd
  C:/Users/ianma/Documents/Simula/LAB7/LAB7.srcs/sources_1/new/LAB7.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/ianma/Downloads/Pratica 6/zybo_board.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/ianma/Downloads/Pratica 6/zybo_board.xdc}}]


synth_design -top LAB7 -part xc7z010clg400-1


write_checkpoint -force -noxdef LAB7.dcp

catch { report_utilization -file LAB7_utilization_synth.rpt -pb LAB7_utilization_synth.pb }
